### ISSUE TITLE
Tasks in jarmonica gradle plugin don't work anymore

### ISSUE THREAD

**Issue by piggylux** [KenjiOhtsuka/harmonica#153]
**Describe the bug**
`jarmonicaUp`, `jarmonicaDown` and `jarmonicaVersion` don't work anymore

**To Reproduce**
Run task.

The following error is returned:
```
Exception in thread "main" java.lang.NoSuchMethodError: org.jetbrains.exposed.sql.Transaction.exec(Ljava/lang/String;)Lkotlin/Unit;
	at com.improve_future.harmonica.core.Connection.execute(Connection.kt:189)
	at com.improve_future.harmonica.core.Connection.<init>(Connection.kt:99)
	at com.improve_future.harmonica.task.JarmonicaTaskMain.createConnection(JarmonicaTaskMain.kt:40)
	at com.improve_future.harmonica.task.JarmonicaUpMain.main(JarmonicaUpMain.kt:34)
```

Kotlin 1.4.0
JDK 1.8

**Comment by KenjiOhtsuka** [comment]
@Sylux6 
Sorry for inconvenience
I will research it

**Comment by viktorisacenko** [comment]
Same problem.
Something new about this issue?

**Comment by KenjiOhtsuka** [comment]
@viktorisacenko 
@Sylux6 
I was so sorry, too busy to fix it.
Today I will solve it.

**Comment by KenjiOhtsuka** [comment]
it looks very strange. In my environment, the migration succeeded.

```
 % ./gradlew jarmonicaUp
Starting a Gradle Daemon, 2 incompatible Daemons could not be reused, use --status for details

> Task :jarmonicaUp
== [Start] Migrate up 20180714192339748 ==
Create Table: normal_table
Create Table: normal_table_for_add
Add column: normal_table_for_add integer_column
Add column: normal_table_for_add varchar_column
Add column: normal_table_for_add decimal_column
Add column: normal_table_for_add boolean_column
Add column: normal_table_for_add blob_column
Add column: normal_table_for_add date_column
Add column: normal_table_for_add time_column
Add column: normal_table_for_add date_time_column
Add column: normal_table_for_add timestamp_column
Add column: normal_table_for_add text_column
Add Index: normal_table integer_column
== [End] Migrate up 20180714192339748 ==
== [Start] Migrate up 20180714194338790 ==
Create Table: not_null_table
Create Table: not_null_table_for_add
Add column: not_null_table_for_add integer_column
Add column: not_null_table_for_add varchar_column
Add column: not_null_table_for_add decimal_column
Add column: not_null_table_for_add boolean_column
Add column: not_null_table_for_add blob_column
Add column: not_null_table_for_add date_column
Add column: not_null_table_for_add time_column
Add column: not_null_table_for_add date_tiem_column
Add column: not_null_table_for_add timestamp_column
Add column: not_null_table_for_add text_column
Add foreign key: not_null_table_for_add.integer_column - normal_table_for_add.id
== [End] Migrate up 20180714194338790 ==
== [Start] Migrate up 20180714194840311 ==
Create Table: default_table
Create Table: default_table_for_add
Add column: default_table_for_add integer_column
Add column: default_table_for_add varchar_column
Add column: default_table_for_add decimal_column
Add column: default_table_for_add boolean_column
Add column: default_table_for_add blob_column
Add column: default_table_for_add date_column_1
Add column: default_table_for_add date_column_2
Add column: default_table_for_add date_column_3
Add column: default_table_for_add time_column_1
Add column: default_table_for_add time_column_2
Add column: default_table_for_add time_column_3
Add column: default_table_for_add date_tiem_column_1
Add column: default_table_for_add date_time_column_2
Add column: default_table_for_add date_time_column_3
Add column: default_table_for_add timestamp_column_1
Add column: default_table_for_add timestamp_column_2
Add column: default_table_for_add timestamp_column_3
Add column: default_table_for_add text_column
== [End] Migrate up 20180714194840311 ==
== [Start] Migrate up 20180714203511949 ==
Create Table: other_table
Create Table: other_table_for_add
Add column: other_table_for_add integer_column
Add column: other_table_for_add varchar_column
Add column: other_table_for_add decimal_column
Add column: other_table_for_add boolean_column
Add column: other_table_for_add date_column
Add column: other_table_for_add time_column
Add column: other_table_for_add date_time_column
Add column: other_table_for_add timestamp_column
Add column: other_table_for_add text_column
== [End] Migrate up 20180714203511949 ==

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.1.1/userguide/command_line_interface.html#sec:command_line_warnings
```

I guess removing exposed library is the solution 🤔

**Comment by KenjiOhtsuka** [comment]
@viktorisacenko 
@Sylux6 
Hello, I removed exposed library.
Please try [2.0.0](https://github.com/KenjiOhtsuka/harmonica/releases/tag/2.0.0).

**Comment by KenjiOhtsuka** [comment]
@viktorisacenko 
@Sylux6 
I will provide a project code.
This, [harmonica_test](https://github.com/KenjiOhtsuka/harmonica_test) is the test project.
I wish it is helpful.

**Comment by piggylux** [comment]
@KenjiOhtsuka We cannot use Exposed in migration classes anymore ?

**Comment by KenjiOhtsuka** [comment]
@Sylux6 
From harmonica, I removed exposed.
But I think you can use Exposed if you add it to gradle.

**Comment by KenjiOhtsuka** [comment]
I removed exposed because it might conflict with the existing Exposed versions. I mean, when the user develops some product with harmonica and it includes Exposed library for the user's product, the Exposed version sometimes differs from the one in Harmonica. 

I thought `lang.NoSuchMethodError` arose in such a situation so I removed exposed from Harmonica.

**Comment by piggylux** [comment]
I'm trying to figure out how to be able to use Exposed api during harmonica migrations since it got removed from the dependencies.

**Comment by KenjiOhtsuka** [comment]
Resolved on the **develop** branch (superseded by Phase 3 Exposed-optionality + Phase 4 plugin-flow tests). No released version carries this fix — the last release predates Phase 3 — so the resolution exists only in the unreleased `develop` codebase.

## Root cause is structurally gone

The report (Kotlin 1.4.0 / JDK 8 era) was:

> `NoSuchMethodError: org.jetbrains.exposed.sql.Transaction.exec(Ljava/lang/String;)Lkotlin/Unit;` at `core:Connection.execute(Connection.kt:189)`

That error happened because `core`'s `Connection` called Exposed's `Transaction.exec(String)` directly — a hard Exposed dependency inside the JDBC core. Phase 3 removed that coupling entirely (PRs #197-#199): `core` now has **zero** `org.jetbrains.exposed.*` imports and drives migrations via plain JDBC transactions. The only Exposed consumer is the opt-in `harmonica-exposed` bridge, which uses the current `exposedTransaction` API — so the class/method mismatch that produced the `NoSuchMethodError` cannot occur on `develop` by construction.

## Both configurations are now tested end-to-end

`PluginFlowTest` (Phase 4, PR #219; part of the 86 green tests on `develop`) creates a fresh test project via Gradle TestKit and runs `harmonicaUp` / `harmonicaDown` against a real SQLite database:

- `harmonicaUpAndDownWithoutExposed` — pure-JDBC `core` path.
- `harmonicaUpAndDownWithExposed` — `exposedTransaction` bridge path.

Both pass, so the plugin flow (the thing this issue reported broken) is verified in exactly the with/without-Exposed split the issue asked for.

## Also note

- The tasks named in the report (`jarmonicaUp` / `jarmonicaDown` / `jarmonicaVersion`) no longer exist as registered tasks — the published plugin id (`com.improve_future.harmonica` → now `harmonica`) registers `harmonicaUp`, `harmonicaDown`, `harmonicaCreate`. The legacy `JarmonicaPlugin` / `Jarmonica*Main` classes remain in source as dormant code, tracked by #26 (naming consolidation) and #97 (tests for the JavaExec subclasses).
- To verify manually against `develop` rather than a release: use a composite build (`pluginManagement { includeBuild(...) }`) or `publishToMavenLocal`, then apply `id("harmonica")` and run the tasks; the same recipe as `PluginFlowTest`.
