### ISSUE TITLE
NoSuchMethodError: Transaction.exec(java.lang.String) running gradle jarmonicaUp with Exposed

### ISSUE THREAD

**Issue by nallwhy** [KenjiOhtsuka/harmonica#157]
**Describe the bug**

`gradle jarmonicaUp` worked well, but it's not working after Exposed is added to deps.

```
3 actionable tasks: 1 executed, 2 up-to-date
Exception in thread "main" java.lang.NoSuchMethodError: 'kotlin.Unit org.jetbrains.exposed.sql.Transaction.exec(java.lang.String)'
	at com.improve_future.harmonica.core.Connection.execute(Connection.kt:189)
	at com.improve_future.harmonica.core.Connection.<init>(Connection.kt:99)
	at com.improve_future.harmonica.task.JarmonicaTaskMain.createConnection(JarmonicaTaskMain.kt:41)
	at com.improve_future.harmonica.task.JarmonicaUpMain.main(JarmonicaUpMain.kt:34)

FAILURE: Build failed with an exception.
```

```
import org.springframework.boot.gradle.tasks.bundling.BootJar

buildscript {
    repositories {
        mavenCentral()
        jcenter()
        maven("https://jitpack.io")
    }

    dependencies {
        classpath("org.jetbrains.kotlin:kotlin-script-util:1.4.30")
        classpath("com.improve_future:harmonica:1.1.26")
    }
}

apply(plugin = "org.springframework.boot")
apply(plugin = "io.spring.dependency-management")
apply(plugin = "org.jetbrains.kotlin.plugin.spring")
apply(plugin = "jarmonica")

dependencies {
    implementation(kotlin("stdlib"))

    implementation("org.springframework.boot:spring-boot-starter")
    implementation("org.springframework.boot:spring-boot-starter-jdbc")

    val exposedVersion = "0.29.1"
    implementation("org.jetbrains.exposed:exposed-core:$exposedVersion")
    implementation("org.jetbrains.exposed:exposed-dao:$exposedVersion")
    implementation("org.jetbrains.exposed:exposed-jdbc:$exposedVersion")
    implementation("org.jetbrains.exposed:exposed-java-time:$exposedVersion")

    runtimeOnly("org.postgresql:postgresql")
    implementation("com.improve_future:harmonica:1.1.26")
    implementation("org.reflections:reflections:0.9.11")
}

tasks.withType<Test> {
    useJUnitPlatform()
}

tasks.getByName<BootJar>("bootJar") {
    enabled = false
}

tasks.getByName<Jar>("jar") {
    enabled = true
}
```

working version:
https://github.com/nallwhy/spring_boot_rumbl/tree/cf7eb2c5ce4d473f71f6de0dc667d189b1ffa6e6

not working version:
https://github.com/nallwhy/spring_boot_rumbl/tree/feeaf1c18dc3d83a5000a5ed5f1c08fda8f005c8

**To Reproduce**
run `gradle jarmonicaUp`

**Expected behavior**
`gradle jarmonicaUp` works well.

**Environment:**
 - OS: Mac OS X 11.2 Big Sur
 - Database: Postgres 12.3
 - JDK/JRE: JDK 11.0.10.hs-adpt , Kotlin 1.4.30 [e.g. JDK 1.8, JDK 1.7, OpenJDK 8]
 - Version: 1.1.26

**Comment by KenjiOhtsuka** [comment]
@nallwhy 
Thanks i will see it

**Comment by KenjiOhtsuka** [comment]
@nallwhy 
This is not tested but I guess version 2.0.0 Harmonica works well.

**Comment by nallwhy** [comment]
How can I use harmonica 2.0.0?
I was failed to add that via jcenter.

**Comment by KenjiOhtsuka** [comment]
@nallwhy 
Oh, really?
sorry for the inconvenience.

um, ... I will investigate the reason.
https://mvnrepository.com/artifact/com.improve_future/harmonica/2.0.0

**Comment by nallwhy** [comment]
This is the error when I change the version of harmonica from 1.1.26 to 2.0.0.

```
> Could not find com.improve_future:harmonica:2.0.0.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/com/improve_future/harmonica/2.0.0/harmonica-2.0.0.pom
       - https://jcenter.bintray.com/com/improve_future/harmonica/2.0.0/harmonica-2.0.0.pom
       - https://jitpack.io/com/improve_future/harmonica/2.0.0/harmonica-2.0.0.pom
       - https://plugins.gradle.org/m2/com/improve_future/harmonica/2.0.0/harmonica-2.0.0.pom
```

**Comment by KenjiOhtsuka** [comment]
@nallwhy 
i added harmonica-2.0.0.pom so could you try again?

**Comment by nallwhy** [comment]
It works! Thx :)
